version: "3.8"

services:
  backend-go:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - comm
  frontend-react:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - comm
networks:
  comm:
    driver: bridge
